<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/Parkeren.Api/Parkeren.Api.csproj" />
    <ProjectReference Include="../../src/Parkeren.TwoParkMock/Parkeren.TwoParkMock.csproj" />
    <ProjectReference Include="../../src/Parkeren.Infrastructure/Parkeren.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.*" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.*" />
    <PackageReference Include="xunit.v3" Version="3.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.*">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <None Update="TestData\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
