import { useEffect,useState,type FormEvent } from "react";import { assignVehicle,createUser,createVehicle,getUsers,getVehicles,setUserActive,setVehicleActive,type UserSummary,type VehicleSummary } from "../../api/client";import { Alert } from "../../design/primitives/Alert";import { Button } from "../../design/primitives/Button";import { Card } from "../../design/primitives/Card";import { Input } from "../../design/primitives/Input";import "./AdminPage.css";
export function AdminPage(){
 const[users,setUsers]=useState<UserSummary[]>([]);const[vehicles,setVehicles]=useState<VehicleSummary[]>([]);const[error,setError]=useState<string>();const[username,setUsername]=useState("");const[pin,setPin]=useState("");const[plate,setPlate]=useState("");const[name,setName]=useState("");const[selectedUser,setSelectedUser]=useState("");const[selectedVehicle,setSelectedVehicle]=useState("");
 async function refresh(){try{const[u,v]=await Promise.all([getUsers(),getVehicles()]);setUsers(u);setVehicles(v);if(!selectedUser&&u[0])setSelectedUser(u[0].id);if(!selectedVehicle&&v[0])setSelectedVehicle(v[0].id);}catch(e){setError(e instanceof Error?e.message:"Laden mislukt.");}}
 useEffect(()=>{void refresh();},[]);
 async function addUser(e:FormEvent){e.preventDefault();setError(undefined);try{await createUser(username,pin);setUsername("");setPin("");await refresh();}catch(e){setError(e instanceof Error?e.message:"Aanmaken mislukt.");}}
 async function addVehicle(e:FormEvent){e.preventDefault();setError(undefined);try{await createVehicle(plate,name);setPlate("");setName("");await refresh();}catch(e){setError(e instanceof Error?e.message:"Aanmaken mislukt.");}}
 async function link(){if(!selectedUser||!selectedVehicle)return;try{await assignVehicle(selectedUser,selectedVehicle);}catch(e){setError(e instanceof Error?e.message:"Toewijzen mislukt.");}}
 return <div className="admin-grid">{error&&<Alert tone="danger">{error}</Alert>}<Card className="admin-card"><h2>Bezoekers</h2><form onSubmit={addUser} className="admin-form"><Input label="Gebruikersnaam" value={username} onChange={e=>setUsername(e.target.value)} required/><Input label="Tijdelijke PIN" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,6))} required/><Button disabled={pin.length!==6}>Bezoeker toevoegen</Button></form><div className="admin-list">{users.map(u=><div className="admin-row" key={u.id}><div><strong>{u.username}</strong><small>{u.role==="Admin"?"Beheerder":"Bezoeker"} · {u.isActive?"Actief":"Inactief"}</small></div><Button variant="secondary" onClick={async()=>{await setUserActive(u.id,!u.isActive);await refresh();}}>{u.isActive?"Deactiveren":"Activeren"}</Button></div>)}</div></Card><Card className="admin-card"><h2>Voertuigen</h2><form onSubmit={addVehicle} className="admin-form"><Input label="Kenteken" value={plate} onChange={e=>setPlate(e.target.value.toUpperCase())} required/><Input label="Omschrijving (optioneel)" value={name} onChange={e=>setName(e.target.value)}/><Button>Voertuig toevoegen</Button></form><div className="admin-list">{vehicles.map(v=><div className="admin-row" key={v.id}><div><strong>{v.licensePlate}</strong><small>{v.displayName||"Geen omschrijving"} · {v.isActive?"Actief":"Inactief"}</small></div><Button variant="secondary" onClick={async()=>{await setVehicleActive(v.id,!v.isActive);await refresh();}}>{v.isActive?"Deactiveren":"Activeren"}</Button></div>)}</div></Card><Card className="admin-card admin-card--wide"><h2>Voertuig toewijzen</h2><div className="admin-assign"><label>Bezoeker<select value={selectedUser} onChange={e=>setSelectedUser(e.target.value)}>{users.filter(u=>u.role==="Visitor").map(u=><option value={u.id} key={u.id}>{u.username}</option>)}</select></label><label>Voertuig<select value={selectedVehicle} onChange={e=>setSelectedVehicle(e.target.value)}>{vehicles.filter(v=>v.isActive).map(v=><option value={v.id} key={v.id}>{v.licensePlate}</option>)}</select></label><Button onClick={link}>Toewijzen</Button></div></Card></div>;
}
