// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parkeren.Infrastructure.Persistence;

#nullable disable

namespace Parkeren.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ParkerenDbContext))]
    [Migration("20261004084150_AddVisitSchedulerAuditEvents")]
    partial class AddVisitSchedulerAuditEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parkeren.Domain.Administration.AdminAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ActorUserId", "CreatedAt");

                    b.ToTable("admin_audit_events", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.HasIndex("RecipientUserId", "CreatedAt");

                    b.HasIndex("RecipientUserId", "ReadAt");

                    b.HasIndex("RecipientUserId", "SourceEventId")
                        .IsUnique()
                        .HasFilter("\"SourceEventId\" IS NOT NULL");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Notifications.NotificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "AggregateId")
                        .IsUnique();

                    b.ToTable("notification_events", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Notifications.PushDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.HasIndex("Status", "LastAttemptAt");

                    b.ToTable("push_deliveries", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Notifications.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.ParkingProvider.ParkingProviderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderProductId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = TRUE");

                    b.HasIndex("ProviderProductId")
                        .IsUnique();

                    b.ToTable("parking_provider_products", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.ParkingProvider.ProviderDiscrepancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderActionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ProviderEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProviderParkingActionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProviderProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProviderStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Open'");

                    b.HasIndex("ProviderParkingActionId");

                    b.HasIndex("ProviderProductId");

                    b.HasIndex("VisitId");

                    b.HasIndex("Status", "LastObservedAt");

                    b.ToTable("provider_discrepancies", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Policies.DefaultParkingPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowOpenEndedVisits")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowVisitExtension")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrentVisits")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("MaxPaidParkingDuration")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("MaxVisitElapsedDuration")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("default_parking_policy", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Policies.ParkingSystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("BudgetWarningThresholdPercentages")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<TimeSpan?>("LongVisitReminderInterval")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("LongVisitWarningAfter")
                        .HasColumnType("interval");

                    b.Property<int>("MaxConcurrentVisits")
                        .HasColumnType("integer");

                    b.Property<bool>("NotifyAdminOnLongVisit")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("parking_system_settings", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Policies.UserPolicyOverride", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("AllowOpenEndedVisits")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AllowVisitExtension")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxConcurrentVisits")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("MaxPaidParkingDuration")
                        .HasColumnType("interval");

                    b.Property<string>("MaxPaidParkingDurationMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeSpan?>("MaxVisitElapsedDuration")
                        .HasColumnType("interval");

                    b.Property<string>("MaxVisitElapsedDurationMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("user_policy_overrides", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.PaidWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("ParkingRuleSetId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParkingRuleSetId", "Day", "Start", "End")
                        .IsUnique();

                    b.ToTable("paid_windows", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.ParkingBudgetPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("MaximumPaidDuration")
                        .HasColumnType("interval");

                    b.Property<Guid?>("ProviderProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderProductId", "ValidFrom");

                    b.ToTable("parking_budget_periods", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.ParkingBudgetWarningState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParkingBudgetPeriodId")
                        .HasColumnType("uuid");

                    b.Property<int>("ThresholdPercentage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParkingBudgetPeriodId", "ThresholdPercentage")
                        .IsUnique();

                    b.ToTable("parking_budget_warning_states", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.ParkingCalendarException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParkingRuleSetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParkingRuleSetId", "Date")
                        .IsUnique();

                    b.ToTable("parking_calendar_exceptions", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.ParkingRuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Continuation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<TimeSpan>("MaxProviderActionDuration")
                        .HasColumnType("interval");

                    b.Property<Guid?>("ProviderProductId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PublicHolidaysAreFree")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderProductId", "ValidFrom");

                    b.ToTable("parking_rule_sets", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.ParkingTariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProviderProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderProductId", "ValidFrom");

                    b.ToTable("parking_tariffs", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Vehicles.UserVehicle", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("user_vehicles", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NormalizedLicensePlate")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedLicensePlate")
                        .IsUnique();

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Visits.ProviderOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("AttemptStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentOperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProviderParkingActionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RequestedEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("ParentOperationId");

                    b.HasIndex("ProviderParkingActionId");

                    b.HasIndex("VisitId");

                    b.HasIndex("ParentOperationId", "Type", "ProviderParkingActionId")
                        .IsUnique()
                        .HasFilter("\"ParentOperationId\" IS NOT NULL");

                    b.ToTable("provider_operations", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Visits.ProviderParkingAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActualEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HistoryStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("PlannedEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PlannedStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderActionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ProviderCostAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("ProviderLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderProductId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderActionId")
                        .IsUnique()
                        .HasFilter("\"ProviderActionId\" IS NOT NULL");

                    b.HasIndex("VisitId");

                    b.ToTable("provider_parking_actions", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Visits.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActualEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DesiredEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndReason")
                        .HasColumnType("integer");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ProviderLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderProductExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProviderProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StartOperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StartedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProviderProductId");

                    b.HasIndex("StartOperationId")
                        .IsUnique();

                    b.HasIndex("StartedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("Status", "StartAt");

                    b.ToTable("visits", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Visits.VisitEndTimeChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PreviousDesiredEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RequestedDesiredEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("VisitId");

                    b.ToTable("visit_end_time_changes", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Visits.VisitSchedulerAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventKey")
                        .IsUnique();

                    b.HasIndex("VisitId", "OccurredAt");

                    b.HasIndex("VisitId", "GroupKey", "OccurredAt");

                    b.ToTable("visit_scheduler_audit_events", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Visits.VisitSchedulerWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndReason")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProviderParkingActionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderParkingActionId")
                        .IsUnique()
                        .HasFilter("\"ProviderParkingActionId\" IS NOT NULL AND \"Type\" = 'ReconcileProviderAction' AND \"Status\" IN ('Pending', 'Claimed')");

                    b.HasIndex("Status", "DueAt");

                    b.HasIndex("VisitId", "Type", "DueAt")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Pending', 'Claimed') AND \"Type\" <> 'ReconcileProviderAction'");

                    b.ToTable("visit_scheduler_work", (string)null);
                });

            modelBuilder.Entity("Parkeren.Domain.Administration.AdminAuditEvent", b =>
                {
                    b.HasOne("Parkeren.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkeren.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Parkeren.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkeren.Domain.Visits.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Parkeren.Domain.Notifications.PushDelivery", b =>
                {
                    b.HasOne("Parkeren.Domain.Notifications.Notification", null)
                        .WithOne()
                        .HasForeignKey("Parkeren.Domain.Notifications.PushDelivery", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkeren.Domain.Notifications.PushSubscription", b =>
                {
                    b.HasOne("Parkeren.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkeren.Domain.ParkingProvider.ProviderDiscrepancy", b =>
                {
                    b.HasOne("Parkeren.Domain.Visits.ProviderParkingAction", null)
                        .WithMany()
                        .HasForeignKey("ProviderParkingActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parkeren.Domain.ParkingProvider.ParkingProviderProduct", null)
                        .WithMany()
                        .HasForeignKey("ProviderProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parkeren.Domain.Visits.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Parkeren.Domain.Policies.UserPolicyOverride", b =>
                {
                    b.HasOne("Parkeren.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Parkeren.Domain.Policies.UserPolicyOverride", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.PaidWindow", b =>
                {
                    b.HasOne("Parkeren.Domain.Rules.ParkingRuleSet", null)
                        .WithMany("PaidWindows")
                        .HasForeignKey("ParkingRuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.ParkingBudgetPeriod", b =>
                {
                    b.HasOne("Parkeren.Domain.ParkingProvider.ParkingProviderProduct", null)
                        .WithMany()
                        .HasForeignKey("ProviderProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.ParkingBudgetWarningState", b =>
                {
                    b.HasOne("Parkeren.Domain.Rules.ParkingBudgetPeriod", null)
                        .WithMany()
                        .HasForeignKey("ParkingBudgetPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.ParkingCalendarException", b =>
                {
                    b.HasOne("Parkeren.Domain.Rules.ParkingRuleSet", null)
                        .WithMany("CalendarExceptions")
                        .HasForeignKey("ParkingRuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.ParkingRuleSet", b =>
                {
                    b.HasOne("Parkeren.Domain.ParkingProvider.ParkingProviderProduct", null)
                        .WithMany()
                        .HasForeignKey("ProviderProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.ParkingTariff", b =>
                {
                    b.HasOne("Parkeren.Domain.ParkingProvider.ParkingProviderProduct", null)
                        .WithMany()
                        .HasForeignKey("ProviderProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Parkeren.Domain.Users.UserSession", b =>
                {
                    b.HasOne("Parkeren.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parkeren.Domain.Vehicles.UserVehicle", b =>
                {
                    b.HasOne("Parkeren.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parkeren.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkeren.Domain.Visits.ProviderOperation", b =>
                {
                    b.HasOne("Parkeren.Domain.Visits.ProviderParkingAction", null)
                        .WithMany()
                        .HasForeignKey("ProviderParkingActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parkeren.Domain.Visits.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Parkeren.Domain.Visits.ProviderParkingAction", b =>
                {
                    b.HasOne("Parkeren.Domain.Visits.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Parkeren.Domain.Visits.Visit", b =>
                {
                    b.HasOne("Parkeren.Domain.ParkingProvider.ParkingProviderProduct", null)
                        .WithMany()
                        .HasForeignKey("ProviderProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parkeren.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("StartedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parkeren.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parkeren.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Parkeren.Domain.Rules.EffectiveParkingPolicySnapshot", "PolicySnapshot", b1 =>
                        {
                            b1.Property<Guid>("VisitId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowOpenEndedVisits")
                                .HasColumnType("boolean")
                                .HasColumnName("PolicyAllowOpenEndedVisits");

                            b1.Property<bool>("AllowVisitExtension")
                                .HasColumnType("boolean")
                                .HasColumnName("PolicyAllowVisitExtension");

                            b1.Property<TimeSpan?>("MaxPaidParkingDuration")
                                .HasColumnType("interval")
                                .HasColumnName("PolicyMaxPaidParkingDuration");

                            b1.Property<TimeSpan?>("MaxVisitElapsedDuration")
                                .HasColumnType("interval")
                                .HasColumnName("PolicyMaxVisitElapsedDuration");

                            b1.HasKey("VisitId");

                            b1.ToTable("visits");

                            b1.WithOwner()
                                .HasForeignKey("VisitId");
                        });

                    b.Navigation("PolicySnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("Parkeren.Domain.Visits.VisitEndTimeChange", b =>
                {
                    b.HasOne("Parkeren.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parkeren.Domain.Visits.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkeren.Domain.Visits.VisitSchedulerAuditEvent", b =>
                {
                    b.HasOne("Parkeren.Domain.Visits.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkeren.Domain.Visits.VisitSchedulerWork", b =>
                {
                    b.HasOne("Parkeren.Domain.Visits.ProviderParkingAction", null)
                        .WithMany()
                        .HasForeignKey("ProviderParkingActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parkeren.Domain.Visits.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkeren.Domain.Rules.ParkingRuleSet", b =>
                {
                    b.Navigation("CalendarExceptions");

                    b.Navigation("PaidWindows");
                });
#pragma warning restore 612, 618
        }
    }
}
